import {
  Utensils,
  Car,
  Banknote,
  TrendingUp,
  Stethoscope,
  ShieldCheck,
  Home,
  Gift,
  User,
  Zap,
  Receipt,
  CreditCard,
  Users,
  Plane,
  Tag,
  Briefcase,
  Award,
  Percent,
  HelpCircle,
  Landmark,
  Coffee,
  Flower2,
  ShoppingBag,
  Repeat,
  ArrowDownCircle,
  Wallet,
  Wifi,
  Smartphone,
  GraduationCap,
  Heart,
  Baby,
  Dumbbell,
  Film,
  Music,
  BookOpen,
  Wrench,
  PiggyBank,
  Droplets,
  Shirt,
  Scissors,
  Fuel,
  ParkingCircle,
  Bus,
  type LucideIcon,
} from "lucide-react";

const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  "food": Utensils,
  "transportation": Car,
  "emi (pl)": Banknote,
  "emi": Landmark,
  "loan emi": Landmark,
  "sip (investment)": TrendingUp,
  "sip": TrendingUp,
  "medical": Stethoscope,
  "term insurance": ShieldCheck,
  "health insurance": ShieldCheck,
  "insurance": ShieldCheck,
  "home": Home,
  "rent": Home,
  "gifts": Gift,
  "personal": User,
  "utilities": Zap,
  "electricity": Zap,
  "living expenses": Receipt,
  "credit card (cc)": CreditCard,
  "credit card": CreditCard,
  "father": Users,
  "family": Users,
  "travel fund": Plane,
  "travel": Plane,
  "other (tax)": Receipt,
  "tax": Receipt,
  "paycheck (salary)": Briefcase,
  "salary": Wallet,
  "bonus": Gift,
  "interest": Percent,
  "cashback": ArrowDownCircle,
  "other": HelpCircle,
  "drinks": Coffee,
  "coffee": Coffee,
  "spa": Flower2,
  "wellness": Flower2,
  "shopping": ShoppingBag,
  "subscriptions": Repeat,
  "subscription": Repeat,
  "internet": Wifi,
  "phone": Smartphone,
  "mobile": Smartphone,
  "education": GraduationCap,
  "charity": Heart,
  "donation": Heart,
  "kids": Baby,
  "childcare": Baby,
  "fitness": Dumbbell,
  "gym": Dumbbell,
  "entertainment": Film,
  "movies": Film,
  "music": Music,
  "books": BookOpen,
  "maintenance": Wrench,
  "repairs": Wrench,
  "savings": PiggyBank,
  "investment": TrendingUp,
  "water": Droplets,
  "clothing": Shirt,
  "grooming": Scissors,
  "fuel": Fuel,
  "gas": Fuel,
  "petrol": Fuel,
  "parking": ParkingCircle,
  "commute": Bus,
  "transit": Bus,
  "grocery": ShoppingBag,
  "groceries": ShoppingBag,
};

export function getCategoryIcon(categoryName: string): LucideIcon {
  return CATEGORY_ICON_MAP[categoryName.toLowerCase().trim()] || Tag;
}
